# Generated by Django 3.0.8 on 2020-09-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='tbl_comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='tbl_post',
        ),
    ]
